config = {
    "actor_lr": 3e-4,
    "critic_lr": 3e-4,
    "hidden_dims": (256, 256, 256),
    "discount": 0.99,
    "dropout_rate": 0.,
    "tau": 0.005,
    "temperature": 1.,
    "clip_grad_norm": 10.0,
    "alpha": 0.992,
    "beta": 0.90,
    "gamma": 0.1,
    
    "f_lr": 4e-4,
    "layer_norm": False,
    "group_norm":True,
    "fourier_scale" : 16,
    "T": 80.0,
    "data_std":0.5,
    "t_min":0.002,
    "time_dim": 8,
    "rho":7.0,
    "num_scales": 1000,
    "num_samples": 50,
    "loss_norm": 'l2',
    "solver":"heun",
    "dsm_target" : False,
    "sde_name" :"KVESDE",
   
}
